### ISSUE TITLE
[Server] 게시글 삭제 시 500에러 발생 이슈

### ISSUE THREAD

**Issue by MignonSS** [codestates-seb/seb44_main_006#128]
## 문제 상황
- 프론트(로컬환경) 에서 게시글 리스트에서 바로 게시글 삭제 시 500에러 발생
- `일정 생성 -> 게시글 생성 -> 답변 생성 -> 게시글 목록 페이지 -> 게시글 삭제` 
- 상세 페이지에서 게시글 삭제 시 에러 발생하지 않음
- 포스트맨으로 테스트할 경우 문제없음
- 500에러 발생 시 서버 에러 로그 NullPointException
<img width="1015" alt="image" src="https://github.com/codestates-seb/seb44_main_006/assets/124571603/2517e662-8c37-485b-853c-f0a1157ac6ee">

### 시도
- course.getPost() 부분이 세팅되지 않아서 발생한 문제라고 생각하고 양방향 매핑 관계 세팅 여부 재확인 (결과 동일)

**Comment by BlancCarte** [comment]
빈태그 입력시 DB에 값이 두번저장되는 문제였고, 해결함 -완-
