### ISSUE TITLE
[Client] 공통 컴포넌트

### ISSUE THREAD

**Issue by R-jisu** [codestates-seb/seb44_main_006#2]
[공통 컴포넌트 모음집](https://www.figma.com/file/sawAGdcqCF7Ceo1BjqEMdp/%EB%94%94%EC%9E%90%EC%9D%B8?type=design&node-id=89-3582&mode=design&t=9VJVntZEdXTOHa6b-0)

<br>

1번 @jieun419 
- [x] 썸네일 카드
- [x] 유저 이미지
   - 마이페이지, 커뮤니티 유저 이미지(해당 유저, 다른 유저)
- [x] 카드
   - 회원, 비회원 다르게 표시
   - 일정과 즐겨찾기일 때 각각 다르게
---
2번 @novice-hero 
- [x] 버튼 
   - 부정, 긍정, action, hover 등
- [x] 좋아요/즐겨찾기 
  - 기능까지 구현
  - 좋아요 상태에 맞게 하트 svg css style표시
  - 즐겨찾기 상태에 맞게 하트 svg css style표시
  - 즐겨찾기 취소/추가 요청에 맞게 POST (아직은 아닌듯)
  - 좋아요 클릭에 맞게 POST (아직은 아닌듯)
- [x] 모달
---
3번 @R-jisu 
- [x] 타이틀 
   - Title, subTitle
- [x] input bar
- [x] textarea
- [x] 댓글 창
- [x] 에러 요소
   - 에러 멘트, 에러 페이지
---
공통 @novice-hero , @R-jisu , @jieun419 
 - [x] 지도(usecallback) 
 - [x] 마커
    - 활성화, 비활성화 상태에 따라 다르게
 - [x] 목적지 컨테이너
    - 순서 표시, 목적지 표시, 2개 이상일 때 회색 선 표시

---

1, 2, 3번 컴포넌트 완료되면 바로 지도로 붙어서 개발 시작
지도 쪽은 세 명이 개발해서 더 나은 쪽으로 나아갈 수 있도록 합치기

---

예상 작업 시간: 3.5d

**Comment by jieun419** [comment]
**1번-카드 컨테이너**의 경우 일단 전부 보여주는 형태로 작업해 두었습니다.
조건에 따라 해당 영역만 안 보이게 하면 될 것 같습니다.

**Comment by novice-hero** [comment]
현재까지 진행상황은 지도, 마커, 선 그리기 컴포넌트까지 구현 완료하였고, 키워드 검색해서 지도에 마커들을 띄우고, 리스트를 보여주는 기능까지 구현 완료했습니다.
