### ISSUE TITLE
[Client] Main page

### ISSUE THREAD

**Issue by R-jisu** [codestates-seb/seb44_main_006#3]
- [x] UI
- [x] 커뮤니티, 일정생성 글자 위에 마우스 hover 시 마우스 커서 custom
- [x] 마우스 커서 바뀐 상태에서 click 시 페이지(커뮤니티/일정 생성) 이동

**Comment by jieun419** [comment]
~~메뉴 클릭시 페이지 이동은 이루어 지지 않습니다. (추후 경로 추가 되면 수정 작업 진행하겠습니다.)~~
- 경로 연결은 했으나 비회원인 경우 schedule 클릭 시 로그인 모달창이 표시되야 하는데 현재 작업 중입니다.
- 각 메뉴 호버시 글자가 변경되는데 이 때 연속적인 반응이 생기는 이슈가 있습니다.
