### ISSUE TITLE
[Client] Header / Footer

### ISSUE THREAD

**Issue by R-jisu** [codestates-seb/seb44_main_006#4]
### 헤더
- [x] 로그인 여부에 따라 UI 변경
- [x] 로고 click 시 메인페이지로 이동
- [x] 로그인 click 시 로그인 모달 on
- [x] 로그아웃 click 시 로그아웃 확인 모달 on
   - 아니오 click 시 모달 off
   - 예 click 시 로그아웃 
- [x] 페이지별 이동 페이지 변경
   -  현재 페이지가 메인페이지/커뮤니티일 경우 페이지 이동 버튼 텍스트가 마이페이지로 바뀌고 click 시 마이페이지로 이동해야함.
   - 현재 페이지가 마이페이지 경우 페이지 이동 버튼 텍스트가 커뮤니티로 바뀌고 click 시 커뮤니티로  이동해야함.

### 푸터
- [x] UI

**Comment by jieun419** [comment]
### 헤더
- 기능적인 요소는 OAuth 작업하면서 같이 진행하겠습니다.
- 마이페이지 생성하자마자 적용 예정입니다.
