### ISSUE TITLE
[Client] Mypage

### ISSUE THREAD

**Issue by R-jisu** [codestates-seb/seb44_main_006#6]
- [x] ui
## 유저 칸
- [x] 일정등록 버튼 클릭 시 일정 등록 페이지로 이동
- [x] 유저 이미지, 닉네임 GET
- [x] 닉네임 수정 시 PATCH 
  -  action : 유저 정보 다시 저장

## 일정 / 즐겨찾기 
- [x] 일정 리스트 GET
- [x] 각 탭에 맞게 리스트 show
- [x] 일정 30개 이상일 경우 일정 등록 버튼 disabled 
- [x] 즐겨찾기 삭제 가능 (공통 컴포넌트 사용)

**Comment by jieun419** [comment]
### 유저 칸
- 유효성 검사 필요합니다.
